/**
 * Bundled background-music starter pack. These tracks are generated by
 * scripts/generate-music.mjs and are CC0 / public domain (see public/music).
 * Served from /public, so the URLs work in the editor preview and the renderer.
 */

export interface MusicTrack {
  id: string;
  name: string;
  url: string;
  description: string;
}

export const MUSIC_LIBRARY: MusicTrack[] = [
  {
    id: "lofi-chill",
    name: "Lo-fi Chill",
    url: "/music/lofi-chill.wav",
    description: "Warm jazzy keys + soft bass — relaxed explainers and vlogs.",
  },
  {
    id: "tech-minimal",
    name: "Tech Minimal",
    url: "/music/tech-minimal.wav",
    description: "Driving sequencer arp + light beat — product and tech content.",
  },
  {
    id: "ambient-glow",
    name: "Ambient Glow",
    url: "/music/ambient-glow.wav",
    description: "Airy bells over a soft pad — calm, cinematic storytelling.",
  },
];
