import type { SceneMood } from "@/compositions/types";

/**
 * Bundled background-music starter pack. These tracks are generated by
 * scripts/generate-music.mjs and are CC0 / public domain (see public/music).
 * Served from /public, so the URLs work in the editor preview and the renderer.
 */

export interface MusicTrack {
  id: string;
  name: string;
  url: string;
  description: string;
  /** Moods this track fits, used to auto-suggest a track from a scene's `mood`/`musicMood`. */
  moods: SceneMood[];
}

export const MUSIC_LIBRARY: MusicTrack[] = [
  {
    id: "lofi-chill",
    name: "Lo-fi Chill",
    url: "/music/lofi-chill.wav",
    description: "Warm jazzy keys + soft bass — relaxed explainers and vlogs.",
    moods: ["calm"],
  },
  {
    id: "tech-minimal",
    name: "Tech Minimal",
    url: "/music/tech-minimal.wav",
    description: "Driving sequencer arp + light beat — product and tech content.",
    moods: ["tech"],
  },
  {
    id: "ambient-glow",
    name: "Ambient Glow",
    url: "/music/ambient-glow.wav",
    description: "Airy bells over a soft pad — calm, cinematic storytelling.",
    moods: ["calm", "inspiring"],
  },
  {
    id: "upbeat-drive",
    name: "Upbeat Drive",
    url: "/music/upbeat-drive.wav",
    description: "Punchy syncopated bass + bright arp — energetic hooks and lists.",
    moods: ["energetic"],
  },
  {
    id: "cinematic-tension",
    name: "Cinematic Tension",
    url: "/music/cinematic-tension.wav",
    description: "Low sustained pad + rising lead — dramatic reveals and stakes.",
    moods: ["dramatic"],
  },
  {
    id: "playful-bounce",
    name: "Playful Bounce",
    url: "/music/playful-bounce.wav",
    description: "Staccato marimba-style plucks — light, fun, quirky beats.",
    moods: ["playful"],
  },
  {
    id: "warm-acoustic",
    name: "Warm Acoustic",
    url: "/music/warm-acoustic.wav",
    description: "Gentle rolling fingerstyle arpeggio — nature and heartfelt moments.",
    moods: ["nature", "inspiring"],
  },
];

/** Pick the bundled track that best matches a scene mood, if any. */
export function suggestBundledTrack(mood: string | undefined): MusicTrack | undefined {
  if (!mood) return undefined;
  return MUSIC_LIBRARY.find((t) => t.moods.includes(mood as SceneMood));
}
